# Generated by Django 4.1.2 on 2022-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
